### ISSUE TITLE
bug: failed to get 'irn_api' as a dependency

### ISSUE THREAD

**Issue by billalxcode** [reown-com/blockchain-api#803]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

error: failed to get `irn_api` as a dependency of package `rpc-proxy v0.113.0 (/home/billal/CryptoProjects/DreyerX/support/blockchain-api)`
Caused by:
  failed to load source for dependency `irn_api`
Caused by:
  Unable to update /home/billal/CryptoProjects/DreyerX/support/blockchain-api/irn/crates/irn_api
Caused by:
  failed to read `/home/billal/CryptoProjects/DreyerX/support/blockchain-api/irn/crates/irn_api/Cargo.toml`
Caused by:
  No such file or directory (os error 2)

### Expected Behavior

The build should complete successfully without dependency errors.

### Steps To Reproduce

1. Clone the repository.
2. Run `just run`.

### Environment

```markdown
- OS: Windows 11
- rustc: rustc 1.77.2 (25ef9e3d8 2024-04-09)
- cargo: cargo 1.77.2 (e52e36006 2024-03-26)
```

**Comment by chris13524** [comment]
Hello! This submodule is a private repo currently, but the parts of this repo that depend on it can be disabled to get it to build

**Comment by billalxcode** [comment]
How to disable that dependency? What happens if I disable the dependency?

**Comment by chris13524** [comment]
We don't currently have a way to disable the dependency. But you are welcome to comment out the relevant code!
